In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
orders_details = pd.concat([pd.read_csv('data/order_products__train.csv'), 
                            pd.read_csv('data/order_products__prior.csv')]).sort_values(by='order_id')
products = pd.read_csv('data/products.csv')
aisles = pd.read_csv('data/aisles.csv')
departments = pd.read_csv('data/departments.csv')

orders = pd.read_csv('data/orders.csv')
sample_subs = pd.read_csv('data/sample_submission.csv')

# prior = pd.read_csv('data/order_products__prior.csv')
# train = pd.read_csv('data/order_products__train.csv')

In [6]:
orders_full_info = pd.merge(left = orders_details, 
                            left_on = 'product_id', 
                            right_on = 'product_id', 
                            how = 'left',
                            right = pd.merge(left = products,
                                             right = departments,
                                             left_on = 'department_id', 
                                             right_on = 'department_id', 
                                             how='left').merge(right = aisles,
                                                               left_on = 'aisle_id', 
                                                               right_on = 'aisle_id', 
                                                               how='left'))

orders_full_info = pd.merge(left=orders_full_info, 
                            right=orders, 
                            left_on='order_id', 
                            right_on='order_id', 
                            how='left').drop(['aisle_id', 'department_id', 'eval_set'], axis=1).sort_values(by='order_id')

In [13]:
# * products
#     * most often reordered products 
#         * by hod/dow/days_since_prior_order
#     * combination of most reordered items?
#     * correlation of reordered items (heat map)

a = orders_full_info[orders_full_info.reordered == 1].groupby(by=['product_id', 'order_dow'])['product_name']
# order_hour_of_day, order_dow, days_since_prior_order }

In [11]:
a.count()

                      order_id  add_to_cart_order  reordered  product_name  \
product_id order_dow
1          0               138                138        138           138
           1               273                273        273           273
           2               159                159        159           159
           3               159                159        159           159
           4               179                179        179           179
           5               204                204        204           204
           6                73                 73         73            73
2          0                 4                  4          4             4
           1                 1                  1          1             1
           2                 1                  1          1             1
           3                 2                  2          2             2
           4                 1                  1          1             1
           5                 2                  2          2             2
           6                 2                  2          2             2
3          0                40                 40         40            40
           1                46                 46         46            46
           2                29                 29         29            29
           3                13                 13         13            13
           4                13                 13         13            13
           5                22                 22         22            22
           6                46                 46         46            46
4          0                41                 41         41            41
           1                23                 23         23            23
           2                22                 22         22            22
           3                13                 13         13            13
           4                18                 18         18            18
           5                21                 21         21            21
           6                23                 23         23            23
5          0                 1                  1          1             1
           1                 1                  1          1             1
...                        ...                ...        ...           ...
49682      5                 6                  6          6             6
           6                 9                  9          9             9
49683      0             15714              15714      15714         15714
           1             12413              12413      12413         12413
           2              8421               8421       8421          8421
           3              7375               7375       7375          7375
           4              7255               7255       7255          7255
           5              7898               7898       7898          7898
           6              9946               9946       9946          9946
49684      5                 1                  1          1             1
49685      1                 3                  3          3             3
           4                 2                  2          2             2
           6                 1                  1          1             1
49686      0                18                 18         18            18
           1                16                 16         16            16
           2                11                 11         11            11
           3                 6                  6          6             6
           4                10                 10         10            10
           5                17                 17         17            17
           6                11                 11         11            11
49687      0                 2                  2          2             2
           2                 2                  2          2             2
           4                 2                  2          2             2
49688      0                 2                  2          2             2
           1                 2                  2          2             2
           2                 2                  2          2             2
           3                 1                  1          1             1
           4                 5                  5          5             5
           5                 3                  3          3             3
           6                 1                  1          1             1

                      department  aisle  user_id  order_number  \
product_id order_dow
1          0                 138    138      138           138
           1                 273    273      273           273
           2                 159    159      159           159
           3                 159    159      159           159
           4                 179    179      179           179
           5                 204    204      204           204
           6                  73     73       73            73
2          0                   4      4        4             4
           1                   1      1        1             1
           2                   1      1        1             1
           3                   2      2        2             2
           4                   1      1        1             1
           5                   2      2        2             2
           6                   2      2        2             2
3          0                  40     40       40            40
           1                  46     46       46            46
           2                  29     29       29            29
           3                  13     13       13            13
           4                  13     13       13            13
           5                  22     22       22            22
           6                  46     46       46            46
4          0                  41     41       41            41
           1                  23     23       23            23
           2                  22     22       22            22
           3                  13     13       13            13
           4                  18     18       18            18
           5                  21     21       21            21
           6                  23     23       23            23
5          0                   1      1        1             1
           1                   1      1        1             1
...                          ...    ...      ...           ...
49682      5                   6      6        6             6
           6                   9      9        9             9
49683      0               15714  15714    15714         15714
           1               12413  12413    12413         12413
           2                8421   8421     8421          8421
           3                7375   7375     7375          7375
           4                7255   7255     7255          7255
           5                7898   7898     7898          7898
           6                9946   9946     9946          9946
49684      5                   1      1        1             1
49685      1                   3      3        3             3
           4                   2      2        2             2
           6                   1      1        1             1
49686      0                  18     18       18            18
           1                  16     16       16            16
           2                  11     11       11            11
           3                   6      6        6             6
           4                  10     10       10            10
           5                  17     17       17            17
           6                  11     11       11            11
49687      0                   2      2        2             2
           2                   2      2        2             2
           4                   2      2        2             2
49688      0                   2      2        2             2
           1                   2      2        2             2
           2                   2      2        2             2
           3                   1      1        1             1
           4                   5      5        5             5
           5                   3      3        3             3
           6                   1      1        1             1

                      order_hour_of_day  days_since_prior_order
product_id order_dow
1          0                        138                     138
           1                        273                     273
           2                        159                     159
           3                        159                     159
           4                        179                     179
           5                        204                     204
           6                         73                      73
2          0                          4                       4
           1                          1                       1
           2                          1                       1
           3                          2                       2
           4                          1                       1
           5                          2                       2
           6                          2                       2
3          0                         40                      40
           1                         46                      46
           2                         29                      29
           3                         13                      13
           4                         13                      13
           5                         22                      22
           6                         46                      46
4          0                         41                      41
           1                         23                      23
           2                         22                      22
           3                         13                      13
           4                         18                      18
           5                         21                      21
           6                         23                      23
5          0                          1                       1
           1                          1                       1
...                                 ...                     ...
49682      5                          6                       6
           6                          9                       9
49683      0                      15714                   15714
           1                      12413                   12413
           2                       8421                    8421
           3                       7375                    7375
           4                       7255                    7255
           5                       7898                    7898
           6                       9946                    9946
49684      5                          1                       1
49685      1                          3                       3
           4                          2                       2
           6                          1                       1
49686      0                         18                      18
           1                         16                      16
           2                         11                      11
           3                          6                       6
           4                         10                      10
           5                         17                      17
           6                         11                      11
49687      0                          2                       2
           2                          2                       2
           4                          2                       2
49688      0                          2                       2
           1                          2                       2
           2                          2                       2
           3                          1                       1
           4                          5                       5
           5                          3                       3
           6                          1                       1

[253670 rows x 10 columns]

In [17]:
int(True)

1

In [16]:
a.head()

,order_id,add_to_cart_order,reordered,product_name,department,aisle,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
product_id,,,,,,,,,,,
1,1185,1185,1185,1185,1185,1185,1185,1185,1185,1185,1185
2,13,13,13,13,13,13,13,13,13,13,13
3,209,209,209,209,209,209,209,209,209,209,209
4,161,161,161,161,161,161,161,161,161,161,161
5,10,10,10,10,10,10,10,10,10,10,10

In [13]:
a

,order_id,add_to_cart_order,reordered,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
product_id,,,,,,,,
1,1.723642e+06,5.836287,1.0,102611.582278,24.593249,2.735865,13.211814,9.179747
2,1.841164e+06,11.769231,1.0,44846.846154,45.461538,2.692308,12.000000,7.538462
3,1.816800e+06,5.483254,1.0,108117.641148,20.397129,2.779904,11.818182,10.291866
4,1.634321e+06,7.478261,1.0,106948.540373,10.975155,2.614907,13.975155,14.962733
5,1.352312e+06,5.700000,1.0,146234.600000,13.600000,3.300000,9.600000,14.400000
6,1.558370e+06,19.333333,1.0,79493.333333,11.666667,4.000000,15.333333,12.333333
7,2.031639e+06,5.769231,1.0,55469.230769,8.000000,2.615385,13.076923,11.615385
8,1.744847e+06,6.711111,1.0,108815.288889,29.288889,2.988889,13.044444,8.988889
9,1.810291e+06,6.500000,1.0,78582.654762,9.845238,2.869048,14.178571,15.166667
10,1.718073e+06,7.874090,1.0,97390.648472,21.267103,2.847889,13.476710,10.251820
11,1.653619e+06,6.400000,1.0,97391.900000,7.466667,2.416667,12.766667,11.816667
12,1.696337e+06,8.265152,1.0,75490.954545,21.537879,3.545455,13.454545,10.537879
13,1.215073e+06,8.000000,1.0,90504.000000,19.000000,4.666667,12.333333,6.666667
14,2.403354e+06,9.000000,1.0,192725.000000,18.000000,4.500000,14.500000,10.500000
15,6.719900e+04,1.000000,1.0,202112.000000,28.000000,2.000000,7.000000,4.000000
16,1.498658e+06,3.500000,1.0,144118.000000,27.500000,4.000000,18.500000,6.500000
17,2.055713e+06,2.500000,1.0,176883.000000,7.500000,3.500000,15.500000,17.000000
18,1.713752e+06,5.273810,1.0,80573.809524,17.440476,3.285714,12.535714,8.880952
20,3.463820e+05,27.000000,1.0,182357.000000,3.000000,0.000000,13.000000,4.000000
21,2.201061e+06,6.000000,1.0,97886.500000,14.000000,3.000000,15.500000,2.500000
22,2.085373e+06,10.052632,1.0,114464.000000,15.947368,2.578947,14.105263,14.578947
23,1.702896e+06,9.875969,1.0,105918.908915,20.327519,2.841085,13.062016,10.761628
24,1.728030e+06,7.166667,1.0,65175.833333,26.833333,2.333333,14.833333,5.833333
25,1.771632e+06,8.922330,1.0,104577.554092,21.661581,2.561026,13.345354,9.961859
26,1.735669e+06,8.606299,1.0,123859.381890,22.303150,3.035433,12.807087,10.051181
27,1.598124e+06,7.974026,1.0,77749.415584,15.766234,2.688312,13.844156,13.025974
28,1.667027e+06,6.527132,1.0,105206.635659,16.824289,2.689922,13.428941,12.090439
29,1.626443e+06,7.647059,1.0,74165.235294,15.541176,2.741176,13.411765,13.505882
30,1.732783e+06,7.048780,1.0,107275.902439,17.975610,2.121951,13.682927,14.634146
31,1.561942e+06,8.687500,1.0,96413.125000,18.437500,1.937500,12.812500,7.625000
...,...,...,...,...,...,...,...,...
49657,1.576832e+06,1.000000,1.0,93985.000000,10.500000,5.500000,13.500000,9.000000
49658,1.373749e+06,5.666667,1.0,63885.285714,16.190476,2.666667,14.523810,10.571429
49659,1.903340e+06,8.600000,1.0,145701.490909,31.690909,2.672727,13.272727,8.090909
49661,1.379490e+06,7.777778,1.0,72244.000000,18.444444,4.000000,13.888889,15.444444
49662,1.280053e+06,5.916667,1.0,125330.416667,5.750000,3.750000,13.833333,16.250000
49663,2.214730e+06,18.333333,1.0,57093.666667,3.666667,2.666667,10.000000,13.666667
49664,1.635507e+06,7.610526,1.0,116653.842105,28.821053,2.947368,12.684211,8.368421
49665,1.494358e+06,10.388889,1.0,82821.629630,32.259259,2.648148,13.166667,7.129630
49667,1.724893e+06,8.689011,1.0,106062.928571,16.894505,2.625275,13.006593,12.201099
49668,1.665750e+06,8.147208,1.0,97788.619289,18.507614,2.710660,13.761421,10.010152
49669,1.969010e+06,15.500000,1.0,76687.500000,31.500000,3.500000,13.000000,7.500000
49670,1.579983e+06,8.426087,1.0,109150.191304,15.652174,3.200000,13.521739,13.260870
49671,1.860945e+06,5.250000,1.0,129313.625000,13.450000,2.850000,12.275000,11.250000
49672,1.742676e+06,6.800000,1.0,128572.000000,12.800000,3.000000,13.200000,9.800000
49673,1.344279e+06,4.818182,1.0,146395.909091,12.636364,2.090909,13.090909,14.363636
49674,1.788728e+06,4.241935,1.0,143700.854839,19.451613,2.741935,14.322581,8.887097
49675,1.653314e+06,5.414634,1.0,126561.317073,15.536585,3.048780,14.268293,11.658537
49676,1.582846e+06,6.250000,1.0,109137.000000,13.750000,2.875000,13.750000,12.208333
49677,1.763630e+06,10.857143,1.0,95960.376623,19.701299,2.480519,12.987013,10.870130
49678,1.684424e+06,9.149068,1.0,102161.745342,16.229814,2.701863,14.093168,13.621118
49679,1.885145e+06,9.951220,1.0,104757.317073,14.829268,3.268293,13.512195,13.170732
49680,1.702876e+06,8.690096,1.0,100607.003195,22.019169,2.591054,13.319489,11.837061
49681,1.461575e+06,6.977273,1.0,109216.795455,14.477273,2.909091,13.795455,10.340909
49682,1.650249e+06,5.921053,1.0,68262.078947,19.131579,3.105263,12.394737,7.868421
49683,1.712962e+06,7.214019,1.0,102441.124975,18.128901,2.601576,13.497508,11.639390
49684,1.367981e+06,4.000000,1.0,169083.000000,2.000000,5.000000,10.000000,28.000000
49685,1.528218e+06,6.833333,1.0,102558.166667,9.666667,2.833333,15.000000,14.000000
49686,1.595058e+06,6.842697,1.0,139356.292135,22.662921,2.775281,12.651685,7.943820
49687,1.608556e+06,5.500000,1.0,97901.333333,16.833333,2.000000,12.500000,14.000000
49688,1.599459e+06,6.562500,1.0,136120.812500,11.625000,3.125000,13.437500,19.125000

# Which products will be reordered?

        
* products
    * most often reordered items { reordered == 1, groupby:product_id;aggregate:[], order_hour_of_day, order_dow, days_since_prior_order }
        * by hod/dow/days_since_prior_order
    * combination of most reordered items?
    * correlation of reordered items (heat map)

* how often user 
    * shops
    * reorders products
        * based on thier: department(category), aisles
        * since last order
            * by department(category), aisles (sedni czas reorederu per deparment, per product
    * most frequently reorder items

* what department of products have highest reorder ratio
    * by daytime
    * by date of the week
    * by month
        
* orders
    * by daytime by day of the week (as a columns)
    * since last order???